
stages:
  - build
  - test

build_project:
  stage: build
  script:
    - xcodebuild clean -project MenuBarPro.xcodeproj -scheme "MenuBar Pro" -destination "platform=macOS" | xcpretty
    - xcodebuild build -project MenuBarPro.xcodeproj -scheme "MenuBar Pro" -destination "platform=macOS" | xcpretty
  tags:
    - xcode_13-0
    - macos_11-3

test_project:
  stage: test
  script:
    - xcodebuild test -project MenubarPro.xcodeproj -scheme "MenuBar Pro" -destination "platform=macOS" | xcpretty -s
  tags:
    - xcode_13-0
    - macos_11-3
